server:
  port: 8080
  servlet:
    context-path: /tatardancespace

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dancespace}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  cache:
    type: redis

oauth:
  yandex:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${OAUTH_REDIRECT_URI:http://localhost:8080/tatardancespace/login/oauth2/code/yandex}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG